// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANz4ExVFkRuY4DqvkTlLnSLwgfMN-ZISY',
    appId: '1:960096798901:web:32d263047148d13d09d6fc',
    messagingSenderId: '960096798901',
    projectId: 'astrologer-f17de',
    authDomain: 'astrologer-f17de.firebaseapp.com',
    databaseURL: 'https://astrologer-f17de-default-rtdb.firebaseio.com',
    storageBucket: 'astrologer-f17de.firebasestorage.app',
    measurementId: 'G-P3V1P4WLHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3eZgH9ygFf4MejU8ioO7_Tpk2sHQtS5k',
    appId: '1:960096798901:android:e6f10eb0290ffecf09d6fc',
    messagingSenderId: '960096798901',
    projectId: 'astrologer-f17de',
    databaseURL: 'https://astrologer-f17de-default-rtdb.firebaseio.com',
    storageBucket: 'astrologer-f17de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD81HDYV7o5kDZ4DwwAyeekyuHZDFfyw-4',
    appId: '1:960096798901:ios:fa8b486dc957f20f09d6fc',
    messagingSenderId: '960096798901',
    projectId: 'astrologer-f17de',
    databaseURL: 'https://astrologer-f17de-default-rtdb.firebaseio.com',
    storageBucket: 'astrologer-f17de.firebasestorage.app',
    iosBundleId: 'ai.astrology.app.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD81HDYV7o5kDZ4DwwAyeekyuHZDFfyw-4',
    appId: '1:960096798901:ios:5d3a8b51e5ee2e4309d6fc',
    messagingSenderId: '960096798901',
    projectId: 'astrologer-f17de',
    databaseURL: 'https://astrologer-f17de-default-rtdb.firebaseio.com',
    storageBucket: 'astrologer-f17de.firebasestorage.app',
    iosBundleId: 'com.example.astrologeradmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANz4ExVFkRuY4DqvkTlLnSLwgfMN-ZISY',
    appId: '1:960096798901:web:92375aa03c65ba4b09d6fc',
    messagingSenderId: '960096798901',
    projectId: 'astrologer-f17de',
    authDomain: 'astrologer-f17de.firebaseapp.com',
    databaseURL: 'https://astrologer-f17de-default-rtdb.firebaseio.com',
    storageBucket: 'astrologer-f17de.firebasestorage.app',
    measurementId: 'G-M4JR7JM9FX',
  );
}
